# Generated by Django 4.0.4 on 2022-06-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=11)),
                ('situacao', models.CharField(max_length=1)),
                ('created_at', models.TimeField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('Cidade_id_cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='happy.cidade')),
                ('Estado_id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='happy.estado')),
            ],
        ),
    ]
