# Generated by Django 4.0.4 on 2022-06-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0003_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('horario', models.TimeField(auto_now=True)),
                ('Instituicoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.institution')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.user')),
            ],
        ),
    ]
